### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by mahmoud** [mahmoud/clastic#16]
Generally a good thing to have, and seems like @okken might have a use case: https://twitter.com/brianokken/status/851474187361411073

**Comment by uyar** [comment]
I'm looking forward to Python 3 support. I haven't used Clastic yet but it looks pretty nice. Once Python 3 is supported, I definitely plan to build an app with it.

**Comment by mahmoud** [comment]
Fixed in 19.0! :)

**Comment by uyar** [comment]
Yes, noticed. Great work, thanks! Looking into using it in a project. I'm checking if I could add Chameleon rendering support. It looks relatively straightforward. I'll let you know if I come up with anything usable.
