### ISSUE TITLE
Dynamic binding example doesn't work

### ISSUE THREAD

**Issue by kevinsl** [mahmoud/clastic#17]
Hello, I was experimenting with clastic and followed the Dynamic Binding example. When changing the parameter name in `hello` it says it should raise an exception. But that doesn't happen for me. Here is my application code:

```
from clastic import Application, render_basic

def hello(first_name='world'):
    return 'Hello, %s' % first_name

routes = [
    ('/', hello, render_basic),
    ('/<name>', hello, render_basic)
]

app = Application(routes)
app.serve()
```

When I always get the response `Hello, World` whether I view the root url or an url with a name (`/` or `/Bob`). But I do not get an exception. Is this correct?

Also, I'm running this is a virtual environment with these packages:

```
clastic==0.5.0
Werkzeug==0.9.4
```

**Comment by mahmoud** [comment]
Oh man, this is coming way late, but I'm reviving my work on clastic, and ran across this. This particular case is just a matter of argument mismatch and default. The url provided `name` and the endpoint function took `first_name`. If `first_name` hadn't had the default of `'world'`, clastic would have raised an exception. Sorry to have taken so long! Keep an eye out for py3-compatible clastic==19.0.0 shortly!
