### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by uyar** [mahmoud/clastic#21]
It would be very helpful to have more documentation, especially in the form of tutorials. I'd be willing to write some, but I'm not confident about "the clastic way of doing things". If I could get a list of keywords worth documenting (like "static file serving", "available middleware", "authentication", "testing" etc.) and some pointers about where to find the information (modules in code base, example application), I could dedicate some time to this.

**Comment by uyar** [comment]
This is too generic to be reported as an issue. I'm closing this my offer to help still stands.

**Comment by mahmoud** [comment]
While it may have been generic, I still really appreciate the offer! I wish I'd said so sooner. I admit, I've been too busy *using* clastic to really document it to the degree it deserves. I'll be in touch to take you up on the offer! :)

**Comment by uyar** [comment]
Sure, I'd be happy to help promoting clastic's use.
