### ISSUE TITLE
Accessing Secure Cookie in request

### ISSUE THREAD

**Issue by shhmendez** [mahmoud/clastic#30]
Mahmoud, 

I'm currently trying to implement a login system for my application. The system involves a couple steps 

1. receive login credentials `(username, password)`
2. Pass creds to login function 
3. create cookie
4. send secure cookie

Now when that user makes a request, their cookies are sent to the server. More specifically, a `SecureCookie`, `userinfo`, is sent to the server by the browser.

Is there a step in `SignedCookieMiddleware` where I can access the cookies in a request? I need that information to perform user validation.

**Comment by shhmendez** [comment]
From what I read in `SignedCookieMiddleware` it looks like `cookie` should contain the cookies in the request. Is that right? 

``` 
def request(self, next, request):
    cookie = self._cookie_type.load_cookie(request,
                                            key=self.cookie_name,
                                            secret_key=self.secret_key)
    response = next(**{self.arg_name: cookie})
```

**Comment by mahmoud** [comment]
Just add "cookie" to your endpoint or middleware arguments and you'll get access to the signed cookie object. Note that this is not all cookies on the request, just the signed cookies.

Here's an example in action: https://github.com/hatnote/montage/blob/27ccd08e98b693ecf4d0f3519fe108eb998ee585/montage/mw.py#L107

**Comment by shhmendez** [comment]
I thought so however, I'm still having issues. This middleware it comes after `SignedCookieMiddleware` 
```
class VerifyUser(Middleware):
    provides = ('user_session',)
    def __init__(self):
        pass
    def request(self,next, request,cookie): 
        response = next({"user_session": {}})
        # cook = cookie.pop("clastic_cookie",None)
        for (k,v) in cookie.items():
            response.set_cookie(k,v)
       
        return response
```
 As you can see it takes `cookie`. Popping the cookie name returns `None` and `cookie.items()` returns an empty list. 

looking at the network request headers I see 

```

Cookie: username=ASD; clastic_cookie="HpTtItFhDAOl7oRniB7priFAlwA=?username=IkFTRCI="
```

So I expect that the server is receiving this

**Comment by shhmendez** [comment]
I was assuming that the name of the unpacked cookie was `clastic_cookie` but that's not what is contained in cookie. Instead `cookie` contains the key value pairs of the items stored in `clastic_cookie`.
I'm not sure why I wasn't receiving that before, but it seems to be working now.

**Comment by mahmoud** [comment]
That's exactly right. Glad you got it sorted!
